### ISSUE TITLE
`jhmod extract` panics when trying to extract assets.nvc

### ISSUE THREAD

**Issue by sector-f** [sector-f/jhmod#18]
```
>> ./jhmod extract -f assets.nvc -u -o './assets' -v
data/unknown/6ce2eaef771a30bb.unknown
data/unknown/2b25de3af944263d.unknown
panic: runtime error: slice bounds out of range [:4] with capacity 1

goroutine 1 [running]:
github.com/sector-f/jhmod/cmd.extractNVC({0x7fff9d60741b?, 0x5bac2a?}, {0xc00012fc78, 0x0, 0x0?}, {0x7fff9d60742c, 0x8}, 0x1, 0x1)
        /home/adam/go/src/github.com/sector-f/jh_extract/cmd/extract.go:100 +0xb3d
github.com/sector-f/jhmod/cmd.extractCmd.func1(0xc000126500?, {0x5ba3d1?, 0x6?, 0x6?})
        /home/adam/go/src/github.com/sector-f/jh_extract/cmd/extract.go:38 +0x325
github.com/spf13/cobra.(*Command).execute(0xc000126500, {0xc0000743c0, 0x6, 0x6})
        /home/adam/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0x70c7a0)
        /home/adam/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/adam/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/sector-f/jhmod/cmd.Execute()
        /home/adam/go/src/github.com/sector-f/jh_extract/cmd/root.go:24 +0x25
main.main()
        /home/adam/go/src/github.com/sector-f/jh_extract/main.go:8 +0x17
```

So, it's panicking when it tries to extract the third file. Let's get some info on that:

```
>> ./jhmod list assets.nvc | head -n 3              
6ce2eaef771a30bb offset=427332 31232B (31232B on disk) flags=0
2b25de3af944263d offset=458564 44520B (44520B on disk) flags=0
eab1186ede4de2ac offset=503084 1B (1B on disk) flags=0
```

The fact that the problematic file is 1B seems _interesting_ at least, but I haven't looked into the issue enough to see how relevant that fact is.

**Comment by sector-f** [comment]
Oh, here's the problem: `magicBytes := string(data[:4])`. So if you're using `-u` and extracting an unknown file that's smaller than 4 bytes, it's gonna panic.

Silly mistake. Should be an easy fix though.
